[package]
name = "oal"
version = "0.1.0"
edition = "2021"

[dependencies]
oal-syntax = { path = "../oal-syntax" }
oal-compiler = { path = "../oal-compiler" }
oal-codegen = { path = "../oal-codegen" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"