[package]
name = "oal-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
oal-syntax = { path = "../oal-syntax" }
oal-compiler = { path = "../oal-compiler" }
indexmap = "1.8"
openapiv3 = "1.0"