[package]
name = "oal-syntax"
version = "0.1.0"
edition = "2021"
authors = ["Emmanuel Bastien <os@ebastien.name>"]
license = "Apache-2.0"
description = "A language for describing web services as OpenAPI"
readme = "../README.md"
homepage = "https://github.com/ebastien/openapi-lang"
repository = "https://github.com/ebastien/openapi-lang"
keywords = ["api"]
categories = ["compilers"]

[dependencies]
oal-model = { path = "../oal-model" }
pest = "2.1.3"
pest_derive = "2.1.0"
enum-map = "2.1.0"
enum-map-derive = "0.10.0"
chumsky = "0.8.0"
string-interner = "0.14.0"
generational_token_list = "0.1.5"
generational-indextree = "1.1.4"