[package]
name = "oal-openapi"
version = "0.1.0"
edition = "2021"

[dependencies]
oal-syntax = { path = "../oal-syntax" }
oal-compiler = { path = "../oal-compiler" }
indexmap = "1.8.1"
openapiv3 = { git = "https://github.com/ebastien/openapiv3", branch = "fix/null-options" }
