[package]
name = "oal-compiler"
version = "0.1.0"
edition = "2021"
authors = ["Emmanuel Bastien <os@ebastien.name>"]
license = "Apache-2.0"
description = "A language for describing web services as OpenAPI"
readme = "../README.md"
homepage = "https://github.com/ebastien/openapi-lang"
repository = "https://github.com/ebastien/openapi-lang"
keywords = ["api"]
categories = ["compilers"]

[dependencies]
oal-syntax = { path = "../oal-syntax" }
indexmap = "1.8.1"
enum-map = "2.1.0"
enum-map-derive = "0.8.0"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8.24"
anyhow = "1.0.57"
url = "2.2.2"
