[package]
name = "oal-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
oal-syntax = { path = "../oal-syntax" }
indexmap = "1.8"
enum-map = "2.1"
enum-map-derive = "0.8"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"